// demo/firebase-react-app/src/components/Setting.tsx
import { ChangeEvent } from "react";
import { CHAIN_CONFIG, CHAIN_CONFIG_TYPE } from "../config/chainConfig";
import { WEB3AUTH_NETWORK, WEB3AUTH_NETWORK_TYPE } from "../config/web3AuthNetwork";
import styles from "../styles/Home.module.css";
import { Web3AuthContext } from "../services/web3auth";
import { useContext } from "react";

interface IProps {
  setNetwork: (network: WEB3AUTH_NETWORK_TYPE) => void;
  setChain: (chain: CHAIN_CONFIG_TYPE) => void;
}

const Setting = ({ setNetwork, setChain }: IProps) => {
  const networkChangeHandler = (e: ChangeEvent<HTMLSelectElement>) => {
    console.log("Settings", e.target.value);
    setNetwork(e.target.value as WEB3AUTH_NETWORK_TYPE);
  };

  const chainChangeHandler = (e: ChangeEvent<HTMLSelectElement>) => {
    console.log("Settings", e.target.value);
    setChain(e.target.value as CHAIN_CONFIG_TYPE);
  };
  const { provider } = useContext(Web3AuthContext);
  const isLoggedIn = provider !== null;

  return (
    <div className={styles.setting}>
      <div className={styles.row}>
        <label htmlFor="network" className={styles.label}>
          Web3Auth Network
        </label>
        <select id="network" onChange={networkChangeHandler} className={styles.select} disabled={isLoggedIn}>
          {Object.keys(WEB3AUTH_NETWORK).map((x: string) => {
            return (
              <option key={x} value={x}>
                {WEB3AUTH_NETWORK[x as WEB3AUTH_NETWORK_TYPE].displayName}
              </option>
            );
          })}
        </select>
      </div>
      <div className={styles.row}>
        <label htmlFor="network" className={styles.label}>
          Blockchain
        </label>
        <select onChange={chainChangeHandler} className={styles.select} disabled={isLoggedIn}>
          {Object.keys(CHAIN_CONFIG).map((x: string) => {
            return (
              <option key={x} value={x}>
                {CHAIN_CONFIG[x as CHAIN_CONFIG_TYPE].displayName}
              </option>
            );
          })}
        </select>
      </div>
    </div>
  );
};

export default Setting;

// demo/angular-app/src/app/setting/setting.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";

import { CHAIN_CONFIG } from "../../config/chains";
import { WEB3AUTH_NETWORK } from "../../config/web3auth-networks";

@Component({
  selector: "app-setting",
  templateUrl: "./setting.component.html",
  styleUrls: ["./setting.component.css"],
})
export class SettingComponent {
  @Output() selectChainEvent = new EventEmitter<string>();

  @Output() selectNetworkEvent = new EventEmitter<string>();

  @Input() isLoggedIn = false;

  networks = WEB3AUTH_NETWORK;

  chains = CHAIN_CONFIG;

  selectChain(e: Event) {
    const el = e.target as HTMLInputElement;
    this.selectChainEvent.emit(el.value);
  }

  selectNetwork(e: Event) {
    const el = e.target as HTMLInputElement;
    this.selectNetworkEvent.emit(el.value);
  }
}

<div class="setting">
    <div class="row">
        <label for="network" class="form-label">Web3Auth Network</label>
        <select id="network" (change)="selectNetwork($event)" class="form-select" [attr.disabled]="isLoggedIn ? '' : null">
            <option *ngFor="let n of networks | keyvalue" value={{n.key}}>{{n.value.displayName}}</option>
        </select>
    </div>
    <div class="row">
        <label for="chain" class="form-label">Chain</label>
        <select id="chain" (change)="selectChain($event)" class="form-select" [attr.disabled]="isLoggedIn ? '' : null">
            <option *ngFor="let c of chains | keyvalue" value={{c.key}}>{{c.value.displayName}}</option>
        </select>
    </div>
</div>
