// demo/vue-app/src/components/loader.vue
<template>
  <div id="w3a-example-modal" class="w3a-example-modal" v-if="isLoading">
    <div class="w3ajs-modal-loader w3a-example-modal__loader">
      <div class="w3a-example-modal__loader-content">
        <div class="w3a-example-modal__loader-info">
          <div class="w3ajs-modal-loader__spinner w3a-spinner">
            <div class="w3a-spinner__body"></div>
            <div class="w3a-spinner__cover"></div>
            <div class="w3a-spinner__head"></div>
          </div>
          <div class="w3ajs-modal-loader__label w3a-spinner-label"></div>
          <div class="w3ajs-modal-loader__message w3a-spinner-message" style="display: none"></div>
        </div>
        <div class="w3a-spinner-power">
          <img src="https://images.web3auth.io/web3auth.svg" />
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "Loader",
  props: {
    isLoading: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {};
  },
});
</script>

// packages/ui/src/components/Loader.tsx
import { ADAPTER_STATUS } from "@web3auth/base";
import { useEffect } from "react";

import { MODAL_STATUS, ModalStatusType } from "../interfaces";
import Icon from "./Icon";
import Image from "./Image";

interface LoaderProps {
  message?: string;
  modalStatus: ModalStatusType;
  label?: string;
  onClose?: () => void;
}

const closeIcon = <Icon iconName="close" />;

export default function Loader(props: LoaderProps) {
  const { message, modalStatus, label, onClose } = props;
  const web3authIcon = <Image imageId="web3auth" />;

  useEffect(() => {
    if (modalStatus === MODAL_STATUS.CONNECTED) {
      setTimeout(() => {
        onClose();
      }, 3000);
    }
  }, [modalStatus]);

  return modalStatus !== MODAL_STATUS.INITIALIZED ? (
    <div className="w3ajs-modal-loader w3a-modal__loader">
      <div className="w3a-modal__loader-content">
        <div className="w3a-modal__loader-info">
          {modalStatus === MODAL_STATUS.CONNECTING && (
            <div className="w3ajs-modal-loader__spinner w3a-spinner">
              <div />
              <div />
              <div />
              <div />
            </div>
          )}

          <div className="w3ajs-modal-loader__label w3a-spinner-label">{label}</div>
          {modalStatus === ADAPTER_STATUS.CONNECTED && <div className="w3ajs-modal-loader__message w3a-spinner-message">{message}</div>}
          {modalStatus === ADAPTER_STATUS.ERRORED && (
            <div className="w3ajs-modal-loader__message w3a-spinner-message w3a-spinner-message--error">{message}</div>
          )}
        </div>
        <div className="w3a-spinner-power">
          <div>Secured by</div>
          {web3authIcon}
        </div>
      </div>
      {(modalStatus === ADAPTER_STATUS.CONNECTED || modalStatus === ADAPTER_STATUS.ERRORED) && (
        <button type="button" className="w3a-header__button w3ajs-loader-close-btn" onClick={onClose}>
          {closeIcon}
        </button>
      )}
    </div>
  ) : null;
}
