// demo/vue-app-modal-vue-composables/src/App.vue
<script setup lang="ts">
import { Web3AuthProvider } from "@web3auth/modal-vue-composables";
import { EthereumPrivateKeyProvider } from "@web3auth/ethereum-provider";
import { CHAIN_NAMESPACES, WEB3AUTH_NETWORK } from "@web3auth/base";
import Home from "./components/Home.vue";
import { WalletServicesPlugin } from "@web3auth/wallet-services-plugin";

const clientId = "BPi5PB_UiIZ-cPz1GtV5i1I2iOSOHuimiXBI0e-Oe_u6X3oVAbCiAZOTEBtTXw4tsluTITPqA8zMsfxIKMjiqNQ"; // get from https://dashboard.web3auth.io

const chainConfig = {
  chainNamespace: CHAIN_NAMESPACES.EIP155,
  chainId: "0xaa36a7",
  rpcTarget: "https://rpc.ankr.com/eth_sepolia",
  // Avoid using public rpcTarget in production.
  // Use services like Infura, Quicknode etc
  displayName: "Ethereum Sepolia Testnet",
  blockExplorerUrl: "https://sepolia.etherscan.io",
  ticker: "ETH",
  tickerName: "Ethereum",
  logo: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
};

const privateKeyProvider = new EthereumPrivateKeyProvider({
  config: { chainConfig: chainConfig }
});

const walletServicesPlugin = new WalletServicesPlugin()
</script>

<template>
  <Web3AuthProvider
    :config="{
      web3AuthOptions: {
        clientId,
        web3AuthNetwork: WEB3AUTH_NETWORK.SAPPHIRE_MAINNET,
        privateKeyProvider,
      },
      plugins: [walletServicesPlugin]
    }"
  >
    <Home />
  </Web3AuthProvider>
</template>

<style scoped></style>

// demo/wagmi-react-app/src/App.tsx
import "./App.css";

import { BUILD_ENV } from "@web3auth/auth";
import { CHAIN_NAMESPACES } from "@web3auth/modal";
import { type Web3AuthContextConfig, Web3AuthProvider } from "@web3auth/modal/react";
import { WagmiProvider } from "@web3auth/modal/react/wagmi";
import { useMemo, useState } from "react";

import Main from "./components/Main";
import styles from "./styles/Home.module.css";

const clientId = "BNJiiG6wVmiMMzApYoCbfD2xU0xxh3cp-t94tgKdwWEuf8Z5DOufWs4SnYiTqdqdA6-pTReQkaiI6z-y9rHxTIM";

const chains: Web3AuthContextConfig["web3AuthOptions"]["chains"] = [
  {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0x1",
    rpcTarget: "https://rpc.ankr.com/eth",
    displayName: "Ethereum Mainnet",
    ticker: "ETH",
    tickerName: "Ethereum",
    blockExplorerUrl: "https://etherscan.io",
    logo: "https://etherscan.io/images/svg/brands/eth.svg",
  },
  {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0x14a34",
    rpcTarget: "https://sepolia.base.org",
    displayName: "Base Sepolia",
    ticker: "ETH",
    tickerName: "Ethereum",
    blockExplorerUrl: "https://sepolia.basescan.org",
    logo: "https://sepolia.basescan.org/images/svg/brands/base.svg",
  },
];

const consentConfig = {
  required: true,
  privacyPolicy: "https://example.com/privacy",
  tncLink: "https://example.com/terms",
};

type ConsentConfigMode = "disabled" | "required";

function App() {
  const [consentConfigMode, setConsentConfigMode] = useState<ConsentConfigMode>("disabled");

  const web3authConfig = useMemo<Web3AuthContextConfig>(() => {
    const web3AuthOptions: Web3AuthContextConfig["web3AuthOptions"] = {
      enableLogging: true,
      web3AuthNetwork: "sapphire_devnet",
      clientId,
      authBuildEnv: BUILD_ENV.TESTING,
      chains,
    };

    if (consentConfigMode === "required") {
      web3AuthOptions.uiConfig = {
        consentConfig,
      };
    }

    return { web3AuthOptions };
  }, [consentConfigMode]);

  return (
    <div className={styles.container}>
      <Web3AuthProvider config={web3authConfig}>
        <WagmiProvider>
          <Main consentConfigMode={consentConfigMode} onConsentConfigModeChange={(value: ConsentConfigMode) => setConsentConfigMode(value)} />
        </WagmiProvider>
      </Web3AuthProvider>
    </div>
  );
}

export default App;
