// demo/vue-app-new2/src/components/AppSettings.vue
<script setup lang="ts">
import { Button, Card, Select, Tab, Tabs, Tag, TextField, Toggle } from "@toruslabs/vue-components";
import { ADAPTER_STATUS, CHAIN_NAMESPACES, ChainNamespaceType, log } from "@web3auth/modal";
import { useWeb3Auth } from "@web3auth/modal/vue";
import { computed, InputHTMLAttributes, ref } from "vue";

import {
  chainConfigs,
  chainNamespaceOptions,
  confirmationStrategyOptions,
  languageOptions,
  loginProviderOptions,
  networkOptions,
  SmartAccountOptions,
} from "../config";
import { formDataStore } from "../store/form";

const formData = formDataStore;

const { status, isConnected, isInitialized, connect } = useWeb3Auth();

const chainOptions = computed(() =>
  chainConfigs[formData.chainNamespace as ChainNamespaceType].map((x) => ({
    name: `${x.chainId} ${x.tickerName}`,
    value: x.chainId,
  }))
);

const adapterOptions = computed(() =>
  formData.chainNamespace === CHAIN_NAMESPACES.EIP155
    ? [
        { name: "coinbase-adapter", value: "coinbase" },
        // { name: "auth-adapter", value: "auth" },
        { name: "torus-evm-adapter", value: "torus-evm" },
        { name: "wallet-connect-v2-adapter", value: "wallet-connect-v2" },
        { name: "injected-adapters", value: "injected-evm" },
      ]
    : [
        { name: "torus-solana-adapter", value: "torus-solana" },
        { name: "wallet-connect-v2-adapter", value: "wallet-connect-v2" },
        { name: "injected-adapters", value: "injected-solana" },
      ]
);

const isDisplay = (_name: string): boolean => {
  return !isConnected.value;
};

const isDisabled = (name: string): boolean => {
  switch (name) {
    case "whiteLabelSettings":
      return !formData.whiteLabel.enable;

    case "walletServicePlugin":
      return formData.chainNamespace !== CHAIN_NAMESPACES.EIP155;

    case "nftCheckoutPlugin":
      return formData.chainNamespace !== CHAIN_NAMESPACES.EIP155;

    case "btnConnect":
      return !isInitialized.value;

    case "smartAccountType":
    case "bundlerUrl":
    case "paymasterUrl":
    case "useAAWithExternalWallet":
      return !formData.useAccountAbstractionProvider;

    case "accountAbstraction":
      return formData.chainNamespace !== CHAIN_NAMESPACES.EIP155;

    default: {
      return false;
    }
  }
};

const activeTab = ref(0);
const onTabChange = (index: number) => {
  activeTab.value = index;
};
const isActiveTab = (index: number) => activeTab.value === index;

const onChainNamespaceChange = (value: string) => {
  log.info("onChainNamespaceChange", value);
  formData.chain = chainConfigs[value as ChainNamespaceType][0].chainId;
  formData.adapters = [];
};
</script>

<template>
  <div v-if="isDisplay('form')" class="grid grid-cols-8 gap-0">
    <div class="col-span-0 sm:col-span-1 lg:col-span-2"></div>
    <Card class="h-auto p-4 sm:p-8 col-span-8 sm:col-span-6 lg:col-span-4 max-sm:!shadow-none max-sm:!border-0">
      <div class="text-2xl font-bold leading-tight text-center sm:text-3xl">{{ $t("app.greeting") }}</div>
      <div class="my-4 font-extrabold leading-tight text-center">
        <Tag v-bind="{ minWidth: 'inherit' }" :class="['uppercase', { '!bg-blue-400 text-white': status === ADAPTER_STATUS.READY }]">
          {{ status }}
        </Tag>
        &nbsp;
        <Tag v-bind="{ minWidth: 'inherit' }" :class="['uppercase', { '!bg-blue-400 text-white': isInitialized }]">
          {{ isInitialized ? "INITIALIZED" : "NOT_INITIALIZE_YET" }}
        </Tag>
      </div>
      <Tabs class="mb-4">
        <Tab variant="underline" :active="isActiveTab(0)" @click="onTabChange(0)">General</Tab>
        <Tab variant="underline" :active="isActiveTab(1)" @click="onTabChange(1)">WhiteLabel</Tab>
        <Tab variant="underline" :active="isActiveTab(2)" @click="onTabChange(2)">Login Provider</Tab>
        <Tab v-if="formData.chainNamespace === CHAIN_NAMESPACES.EIP155" variant="underline" :active="isActiveTab(3)" @click="onTabChange(3)">
          Wallet Plugin
        </Tab>
        <Tab v-if="formData.chainNamespace === CHAIN_NAMESPACES.EIP155" variant="underline" :active="isActiveTab(4)" @click="onTabChange(4)">
          NFT Checkout Plugin
        </Tab>
        <Tab v-if="formData.chainNamespace === CHAIN_NAMESPACES.EIP155" variant="underline" :active="isActiveTab(5)" @click="onTabChange(5)">
          Account Abstraction Provider
        </Tab>
      </Tabs>
      <Card v-if="isActiveTab(0)" class="grid grid-cols-1 gap-2 px-4 py-4" :shadow="false">
        <Select
          v-model="formData.network"
          data-testid="selectNetwork"
          :label="$t('app.network')"
          :aria-label="$t('app.network')"
          :placeholder="$t('app.network')"
          :options="networkOptions"
        />
        <Select
          v-model="formData.chainNamespace"
          data-testid="selectChainNamespace"
          :label="$t('app.chainNamespace')"
          :aria-label="$t('app.chainNamespace')"
          :placeholder="$t('app.chainNamespace')"
          :options="chainNamespaceOptions"
          @update:model-value="onChainNamespaceChange"
        />
        <Select
          v-model="formData.chain"
          data-testid="selectChain"
          :label="$t('app.chain')"
          :aria-label="$t('app.chain')"
          :placeholder="$t('app.chain')"
          :options="chainOptions"
        />
        <Select
          v-model="formData.adapters"
          data-testid="selectAdapters"
          :label="$t('app.adapters')"
          :aria-label="$t('app.adapters')"
          :placeholder="$t('app.adapters')"
          :options="adapterOptions"
          multiple
          :show-check-box="true"
        />
        <Toggle
          v-model="formData.showWalletDiscovery"
          data-testid="showWalletDiscovery"
          :show-label="true"
          :size="'small'"
          :label-disabled="$t('app.showWalletDiscovery')"
          :label-enabled="$t('app.showWalletDiscovery')"
          class="mb-2"
        />
      </Card>
      <Card v-if="isActiveTab(1)" class="grid grid-cols-1 gap-2 px-4 py-4 sm:grid-cols-2" :shadow="false">
        <Toggle
          v-model="formData.whiteLabel.enable"
          data-testid="whitelabel"
          :show-label="true"
          :size="'small'"
          :label-disabled="$t('app.whiteLabel.title')"
          :label-enabled="$t('app.whiteLabel.title')"
          class="mb-2"
        />
        <Toggle
          id="useLogoLoader"
          v-model="formData.whiteLabel.config.useLogoLoader"
          :show-label="true"
          :size="'small'"
          :label-disabled="$t('app.whiteLabel.useLogoLoader')"
          :label-enabled="$t('app.whiteLabel.useLogoLoader')"
          :disabled="isDisabled('whiteLabelSettings')"
        />
        <TextField
          v-model="formData.whiteLabel.config.appName"
          :label="$t('app.whiteLabel.appName')"
          :aria-label="$t('app.whiteLabel.appName')"
          :placeholder="$t('app.whiteLabel.appName')"
          :disabled="isDisabled('whiteLabelSettings')"
        />
        <Select
          v-model="formData.whiteLabel.config.defaultLanguage"
          :label="$t('app.whiteLabel.defaultLanguage')"
          :aria-label="$t('app.whiteLabel.defaultLanguage')"
          :placeholder="$t('app.whiteLabel.defaultLanguage')"
          :options="languageOptions"
          :disabled="isDisabled('whiteLabelSettings')"
        />
        <TextField
          v-model="formData.whiteLabel.config.appUrl"
          :label="$t('app.whiteLabel.appUrl')"
          :aria-label="$t('app.whiteLabel.appUrl')"
          :placeholder="$t('app.whiteLabel.appUrl')"
          :disabled="isDisabled('whiteLabelSettings')"
          class="col-span-2"
        />
        <TextField
          v-model="formData.whiteLabel.config.logoLight"
          :label="$t('app.whiteLabel.logoLight')"
          :aria-label="$t('app.whiteLabel.logoLight')"
          :placeholder="$t('app.whiteLabel.logoLight')"
          :disabled="isDisabled('whiteLabelSettings')"
        />
        <TextField
          v-model="formData.whiteLabel.config.logoDark"
          :label="$t('app.whiteLabel.logoDark')"
          :aria-label="$t('app.whiteLabel.logoDark')"
          :placeholder="$t('app.whiteLabel.logoDark')"
          :disabled="isDisabled('whiteLabelSettings')"
        />

        <TextField
          :model-value="formData.whiteLabel.config.theme?.primary"
          :label="$t('app.whiteLabel.primaryColor')"
          :aria-label="$t('app.whiteLabel.primaryColor')"
          :placeholder="$t('app.whiteLabel.primaryColor')"
          :disabled="isDisabled('whiteLabelSettings')"
        >
          <template #endIconSlot>
            <input
              id="primary-color-picker"
              class="color-picker"
              type="color"
              :value="formData.whiteLabel.config.theme?.primary"
              @input="
                (e) => {
                  const color = (e.target as InputHTMLAttributes).value;
                  formData.whiteLabel.config.theme = { ...formData.whiteLabel.config.theme, primary: color };
                }
              "
            />
          </template>
        </TextField>
        <TextField
          :model-value="formData.whiteLabel.config.theme?.onPrimary"
          :label="$t('app.whiteLabel.onPrimaryColor')"
          :aria-label="$t('app.whiteLabel.onPrimaryColor')"
          :placeholder="$t('app.whiteLabel.onPrimaryColor')"
          :disabled="isDisabled('whiteLabelSettings')"
        >
          <template #endIconSlot>
            <input
              id="primary-color-picker"
              class="color-picker"
              type="color"
              :value="formData.whiteLabel.config.theme?.onPrimary"
              @input="
                (e) => {
                  const color = (e.target as InputHTMLAttributes).value;
                  formData.whiteLabel.config.theme = { ...formData.whiteLabel.config.theme, onPrimary: color };
                }
              "
            />
          </template>
        </TextField>
      </Card>
      <Card v-if="isActiveTab(2)" class="grid grid-cols-1 gap-2 px-4 py-4" :shadow="false">
        <Select
          v-model="formData.loginProviders"
          data-testid="selectLoginProviders"
          :label="$t('app.loginProviders')"
          :aria-label="$t('app.loginProviders')"
          :placeholder="$t('app.loginProviders')"
          :options="loginProviderOptions"
          multiple
          class=""
        />
        <Card v-for="p in formData.loginProviders" :key="p" :shadow="false" class="grid grid-cols-1 gap-2 px-4 py-4 sm:grid-cols-3">
          <div class="font-bold leading-tight text-left sm:col-span-2">{{ p }}</div>
          <Toggle
            v-model="formData.loginMethods[p].mainOption"
            :show-label="true"
            :size="'small'"
            :label-disabled="$t('app.loginMethod.mainOption')"
            :label-enabled="$t('app.loginMethod.mainOption')"
          />
          <TextField
            v-model="formData.loginMethods[p].name"
            :label="$t('app.loginMethod.name')"
            :aria-label="$t('app.loginMethod.name')"
            :placeholder="$t('app.loginMethod.name')"
          />
          <TextField
            v-model="formData.loginMethods[p].description"
            :label="$t('app.loginMethod.description')"
            :aria-label="$t('app.loginMethod.description')"
            :placeholder="$t('app.loginMethod.description')"
            class="sm:col-span-2"
          />
          <TextField
            v-model="formData.loginMethods[p].logoHover"
            :label="$t('app.loginMethod.logoHover')"
            :aria-label="$t('app.loginMethod.logoHover')"
            :placeholder="$t('app.loginMethod.logoHover')"
          />
          <TextField
            v-model="formData.loginMethods[p].logoLight"
            :label="$t('app.loginMethod.logoLight')"
            :aria-label="$t('app.loginMethod.logoLight')"
            :placeholder="$t('app.loginMethod.logoLight')"
          />
          <TextField
            v-model="formData.loginMethods[p].logoDark"
            :label="$t('app.loginMethod.logoDark')"
            :aria-label="$t('app.loginMethod.logoDark')"
            :placeholder="$t('app.loginMethod.logoDark')"
          />
          <Toggle
            v-model="formData.loginMethods[p].showOnModal"
            :show-label="true"
            :size="'small'"
            :label-disabled="$t('app.loginMethod.showOnModal')"
            :label-enabled="$t('app.loginMethod.showOnModal')"
          />
          <Toggle
            v-model="formData.loginMethods[p].showOnDesktop"
            :show-label="true"
            :size="'small'"
            :label-disabled="$t('app.loginMethod.showOnDesktop')"
            :label-enabled="$t('app.loginMethod.showOnDesktop')"
          />
          <Toggle
            v-model="formData.loginMethods[p].showOnMobile"
            :show-label="true"
            :size="'small'"
            :label-disabled="$t('app.loginMethod.showOnMobile')"
            :label-enabled="$t('app.loginMethod.showOnMobile')"
          />
        </Card>
      </Card>
      <Card v-if="isActiveTab(3)" class="grid grid-cols-1 gap-2 px-4 py-4" :shadow="false">
        <Toggle
          v-model="formData.walletPlugin.enable"
          :disabled="isDisabled('walletServicePlugin')"
          :show-label="true"
          :size="'small'"
          :label-disabled="$t('app.walletPlugin.title')"
          :label-enabled="$t('app.walletPlugin.title')"
          class="mb-2"
        />
        <Select
          v-model="formData.walletPlugin.confirmationStrategy"
          data-testid="selectLoginProviders"
          :label="$t('app.walletPlugin.confirmationStrategy')"
          :aria-label="$t('app.walletPlugin.confirmationStrategy')"
          :placeholder="$t('app.walletPlugin.confirmationStrategy')"
          :options="confirmationStrategyOptions"
          class=""
        />
      </Card>
      <Card v-if="isActiveTab(4)" class="grid grid-cols-1 gap-2 px-4 py-4" :shadow="false">
        <Toggle
          v-model="formData.nftCheckoutPlugin.enable"
          :disabled="isDisabled('nftCheckoutPlugin')"
          :show-label="true"
          :size="'small'"
          :label-disabled="$t('app.nftCheckoutPlugin.title')"
          :label-enabled="$t('app.nftCheckoutPlugin.title')"
          class="mb-2"
        />
      </Card>
      <Card v-if="isActiveTab(5)" class="grid grid-cols-1 gap-2 px-4 py-4" :shadow="false">
        <Toggle
          v-model="formData.useAccountAbstractionProvider"
          data-testid="accountAbstractionProvider"
          :show-label="true"
          :size="'small'"
          :label-disabled="$t('app.accountAbstractionProvider.title')"
          :label-enabled="$t('app.accountAbstractionProvider.title')"
          class="my-2"
        />
        <Toggle
          v-model="formData.useAAWithExternalWallet"
          data-testid="useAAWithExternalWallet"
          :show-label="true"
          :size="'small'"
          :label-disabled="$t('app.accountAbstractionProvider.useAAWithExternalWallet')"
          :label-enabled="$t('app.accountAbstractionProvider.useAAWithExternalWallet')"
          class="my-2"
          :disabled="isDisabled('useAAWithExternalWallet')"
        />
        <Select
          v-model="formData.smartAccountType"
          data-testid="smartAccountType"
          :label="$t('app.accountAbstractionProvider.smartAccountType')"
          :aria-label="$t('app.accountAbstractionProvider.smartAccountType')"
          :placeholder="$t('app.accountAbstractionProvider.smartAccountType')"
          :options="SmartAccountOptions"
          :disabled="isDisabled('smartAccountType')"
        />
        <TextField
          v-model="formData.bundlerUrl"
          :label="$t('app.accountAbstractionProvider.bundlerUrl')"
          :aria-label="$t('app.accountAbstractionProvider.bundlerUrl')"
          :placeholder="$t('app.accountAbstractionProvider.bundlerUrl')"
          :disabled="isDisabled('bundlerUrl')"
        />
        <TextField
          v-model="formData.paymasterUrl"
          :label="$t('app.accountAbstractionProvider.paymasterUrl')"
          :aria-label="$t('app.accountAbstractionProvider.paymasterUrl')"
          :placeholder="$t('app.accountAbstractionProvider.paymasterUrl')"
          :disabled="isDisabled('paymasterUrl')"
        />
      </Card>
      <div class="flex justify-center mt-5">
        <Button
          :class="['w-full !h-auto group py-3 rounded-full flex items-center justify-center']"
          data-testid="loginButton"
          type="button"
          block
          size="md"
          pill
          :disabled="isDisabled('btnConnect')"
          @click="connect"
        >
          Connect
        </Button>
      </div>
      <div class="px-0 mt-4 mb-5 text-sm font-normal text-app-gray-900 dark:text-app-gray-200">
        Reach out to us at
        <a class="underline text-app-primary-600 dark:text-app-primary-500" href="mailto:hello@tor.us">hello@tor.us</a>
        or
        <a class="underline text-app-primary-600 dark:text-app-primary-500" href="https://t.me/torusdev">telegram group</a>
        .
      </div>
    </Card>
  </div>
</template>

// demo/react-app-new/src/components/AppSettings.tsx
import React, { useEffect, useState } from "react";
import { useWeb3Auth } from "@web3auth/modal-react-hooks";
import { useTranslation } from "react-i18next";
import { useAppContext } from "../context";
import useOptions from "../hooks/useOptions";
import {
  ChainNamespaceType,
  WEB3AUTH_NETWORK_TYPE,
} from "@web3auth/base";

import { Button, Card, ColorPicker, Select, Tabs, Tag, TextField, Toggle } from "./CommonUI";
import { LANGUAGE_TYPE, LOGIN_PROVIDER_TYPE } from "@web3auth/auth";

const AppSettings: React.FC = () => {
  const {
    network,
    chainNamespace,
    chain,
    adapters,
    setNetWork,
    setChainNamespace,
    setChain,
    setAdapters,
    whiteLabel,
    setWhiteLabel,
    loginProviders,
    setLoginProviders,
    loginMethods,
    setLoginMethods,
    walletPlugin,
    setWalletPlugin,
  } = useAppContext();
  const { t } = useTranslation();
  const { status, logout, isConnected, isInitialized, connect } = useWeb3Auth();

  const { networkOptions, chainNamespaceOptions, chainOptions, adapterOptions, loginProviderOptions, languageOptions } = useOptions();

  const [activeTab, setActiveTab] = useState("General");

  const handleTabClick = (tab: string) => {
    setActiveTab(tab);
  };

  const onChangeAdapters = (value: string[]) => {
    const [adapter] = value;

    if (adapters.includes(adapter)) {
      setAdapters(adapters.filter((x) => x !== adapter));
    } else {
      setAdapters(adapters.concat(adapter));
    }
  };

  const onChangeLoginProviders = (value: string[]) => {
    const [loginProvider] = value;

    if (loginProviders.includes(loginProvider as LOGIN_PROVIDER_TYPE)) {
      setLoginProviders(loginProviders.filter((x) => x !== loginProvider));
    } else {
      setLoginProviders(loginProviders.concat(loginProvider as LOGIN_PROVIDER_TYPE));
    }
  };

  const onChangeLoginMethods = (loginProvider: LOGIN_PROVIDER_TYPE, fieldName: string, value: string) => {
    const method = loginMethods[loginProvider];
    switch (fieldName) {
      case "name":
        setLoginMethods({ ...loginMethods, [loginProvider]: { ...method, name: value } });
        break;
      case "description":
        setLoginMethods({ ...loginMethods, [loginProvider]: { ...method, description: value } });
        break;
      case "logoHover":
        setLoginMethods({ ...loginMethods, [loginProvider]: { ...method, logoHover: value } });
        break;
      case "logoLight":
        setLoginMethods({ ...loginMethods, [loginProvider]: { ...method, logoLight: value } });
        break;
      case "logoDark":
        setLoginMethods({ ...loginMethods, [loginProvider]: { ...method, logoDark: value } });
        break;
      case "mainOption":
        setLoginMethods({ ...loginMethods, [loginProvider]: { ...method, mainOption: !method.mainOption } });
        break;
      case "showOnModal":
        setLoginMethods({ ...loginMethods, [loginProvider]: { ...method, showOnModal: !method.showOnModal } });
        break;
      case "showOnDesktop":
        setLoginMethods({ ...loginMethods, [loginProvider]: { ...method, showOnDesktop: !method.showOnDesktop } });
        break;
      case "showOnMobile":
        setLoginMethods({ ...loginMethods, [loginProvider]: { ...method, showOnMobile: !method.showOnMobile } });
        break;
      default:
        break;
    }
  };

  const onToggle = (fieldName: string) => {
    switch (fieldName) {
      case "whiteLabel.enable":
        setWhiteLabel({ enable: !whiteLabel.enable, config: whiteLabel.config });
        break;
      case "whiteLabel.config.useLogoLoader":
        setWhiteLabel({ enable: whiteLabel.enable, config: { ...whiteLabel.config, useLogoLoader: !whiteLabel.config.useLogoLoader } });
        break;
      case "walletPlugin.enable":
        setWalletPlugin({ enable: !walletPlugin.enable, logoLight: walletPlugin.logoLight, logoDark: walletPlugin.logoDark });
        break;
      default:
        break;
    }
  };

  const onTextFieldChange = (fieldName: string, value: string) => {
    switch (fieldName) {
      case "whiteLabel.config.appName":
        setWhiteLabel({ enable: whiteLabel.enable, config: { ...whiteLabel.config, appName: value } });
        break;
      case "whiteLabel.config.appUrl":
        setWhiteLabel({ enable: whiteLabel.enable, config: { ...whiteLabel.config, appUrl: value } });
        break;
      case "whiteLabel.config.logoLight":
        setWhiteLabel({ enable: whiteLabel.enable, config: { ...whiteLabel.config, logoLight: value } });
        break;
      case "whiteLabel.config.logoDark":
        setWhiteLabel({ enable: whiteLabel.enable, config: { ...whiteLabel.config, logoDark: value } });
        break;
      case "walletPlugin.logoLight":
        setWalletPlugin({ enable: walletPlugin.enable, logoLight: value, logoDark: walletPlugin.logoDark });
        break;
      case "walletPlugin.logoDark":
        setWalletPlugin({ enable: walletPlugin.enable, logoLight: walletPlugin.logoLight, logoDark: value });
        break;
      
      default:
        break;
    }
  };

  const onChangLanguage = (value: string) => {
    setWhiteLabel({ enable: whiteLabel.enable, config: { ...whiteLabel.config, defaultLanguage: value as LANGUAGE_TYPE } });
  }

  return !isConnected && (
    <div className="grid grid-cols-8 gap-0">
      <div className="col-span-0 sm:col-span-1 lg:col-span-2"></div>
      <Card className="h-auto px-8 py-8 col-span-8 sm:col-span-6 lg:col-span-4">
        <div className="text-3xl font-bold leading-tight text-center">{t("app.greeting")}</div>
        <div className="leading-tight font-extrabold text-center mb-12">
          <Tag text={status} /> 
          &nbsp;
          <Tag text={isInitialized ? "INITIALIZED" : "NOT_INITIALIZE_YET"} />
        </div>
        <Tabs tabs={["General", "WhiteLabel", "Login Provider", "Wallet Plugin"]} activeTab={activeTab} onTabClick={handleTabClick} />
        {activeTab === "General" && (
          <Card className="grid grid-cols-1 gap-2 py-4 px-4 shadow-none">
            <Select
              label={t('app.network')}
              options={networkOptions}
              onChange={(value) => setNetWork(value[0] as WEB3AUTH_NETWORK_TYPE)}
              value={[network]}
            />
            <Select
              label={t('app.chainNamespace')}
              options={chainNamespaceOptions}
              value={[chainNamespace]}
              onChange={(value) => setChainNamespace(value[0] as ChainNamespaceType)}
            />
            <Select label={t('app.chain')} options={chainOptions} value={[chain]} onChange={(value) => setChain(value[0])} />
            <Select label={t('app.adapters')} options={adapterOptions} value={adapters} onChange={onChangeAdapters} multiple={true} />
          </Card>
        )}
        {activeTab === "WhiteLabel" && (
          <Card className="grid grid-cols-1 sm:grid-cols-2 gap-2 py-4 px-4 shadow-none">
            <Toggle label={t("app.whiteLabel.title")} isOn={Boolean(whiteLabel.enable)} onToggle={() => onToggle("whiteLabel.enable")} />
            <Toggle
              label={t("app.whiteLabel.useLogoLoader")}
              isOn={Boolean(whiteLabel.config.useLogoLoader)}
              onToggle={() => onToggle("whiteLabel.config.useLogoLoader")}
              disabled={!whiteLabel.enable}
            />
            <TextField
              label={t("app.whiteLabel.appName")}
              value={whiteLabel.config.appName || ""}
              onChange={(value) => onTextFieldChange("whiteLabel.config.appName", value)}
              disabled={!whiteLabel.enable}
            />
            <Select
              label={t("app.whiteLabel.defaultLanguage")}
              options={languageOptions}
              value={[whiteLabel.config.defaultLanguage || ''] as LANGUAGE_TYPE[]}
              onChange={(value) => onChangLanguage(value[0])}
              disabled={!whiteLabel.enable}
            />
            <TextField className="col-span-2" label={t("app.whiteLabel.appUrl")} value={whiteLabel.config.appUrl || ""} onChange={(value) => {}} disabled={!whiteLabel.enable} />
            <TextField label={t("app.whiteLabel.logoLight")} value={whiteLabel.config.logoLight || ""} onChange={(value) => {}} disabled={!whiteLabel.enable} />
            <TextField label={t("app.whiteLabel.logoDark")} value={whiteLabel.config.logoDark || ""} onChange={(value) => {}} disabled={!whiteLabel.enable}/>
            <ColorPicker label={t("app.whiteLabel.primary")} color={whiteLabel.config.theme?.primary || ""} onChange={(color) => {}} disabled={!whiteLabel.enable} />
            <ColorPicker label={t("app.whiteLabel.primaryColor")} color={whiteLabel.config.theme?.onPrimary || ""} onChange={(color) => {}} disabled={!whiteLabel.enable} />
          </Card>
        )}
        {activeTab === "Login Provider" && (
          <Card className="grid grid-cols-1 gap-2 py-4 px-4 shadow-none">
            <Select
              label={t('app.loginProvider')}
              options={loginProviderOptions}
              value={loginProviders}
              onChange={onChangeLoginProviders}
              multiple={true}
            />
            {loginProviders.map((p, index) => {
              const method = loginMethods[p];
              const { name, description, logoHover, logoLight, logoDark, mainOption, showOnModal, showOnDesktop, showOnMobile } = method;
              return (
                <Card key={index} className="px-4 py-4 grid grid-cols-1 sm:grid-cols-2 gap-2 shadow-none border">
                  <div className="font-bold leading-tight text-left sm:col-span-2">{p}</div>
                  <Toggle label={t("app.loginProvider.mainOption")} isOn={mainOption} onToggle={() => onChangeLoginMethods(p, "mainOption", "")} />
                  <TextField label={t("app.loginProvider.name")} value={name} onChange={(value) => onChangeLoginMethods(p, "name", value)} />
                  <TextField
                    label={t("app.loginProvider.description")}
                    value={description}
                    onChange={(value) => onChangeLoginMethods(p, "description", value)}
                  />
                  <TextField
                    label={t("app.loginProvider.logoHover")}
                    value={logoHover}
                    onChange={(value) => onChangeLoginMethods(p, "logoHover", value)}
                  />
                  <TextField
                    label={t("app.loginProvider.logoLight")}
                    value={logoLight}
                    onChange={(value) => onChangeLoginMethods(p, "logoLight", value)}
                  />
                  <TextField
                    label={t("app.loginProvider.logoDark")}
                    value={logoDark}
                    onChange={(value) => onChangeLoginMethods(p, "logoDark", value)}
                  />

                  <Toggle label={t("app.loginProvider.showOnModal")} isOn={showOnModal} onToggle={() => onChangeLoginMethods(p, "showOnModal", "")} />
                  <Toggle
                    label={t("app.loginProvider.showOnDesktop")}
                    isOn={showOnDesktop}
                    onToggle={() => onChangeLoginMethods(p, "showOnDesktop", "")}
                  />
                  <Toggle
                    label={t("app.loginProvider.showOnMobile")}
                    isOn={showOnMobile}
                    onToggle={() => onChangeLoginMethods(p, "showOnMobile", "")}
                  />
                </Card>
              );
            })}
          </Card>
        )}
        {activeTab === "Wallet Plugin" && (
          <Card className="grid grid-cols-1 gap-2 py-4 px-4 shadow-none">
            <Toggle label={t("app.walletPlugin.enable")} isOn={Boolean(walletPlugin.enable)} onToggle={() => onToggle("walletPlugin.enable")} />
            <TextField
              label={t("app.walletPlugin.logoLight")}
              value={walletPlugin.logoLight || ""}
              onChange={(value) => onTextFieldChange("walletPlugin.logoLight", value)}
              disabled={!walletPlugin.enable}
            />
            <TextField
              label={t("app.walletPlugin.logoDark")}
              value={walletPlugin.logoDark || ""}
              onChange={(value) => onTextFieldChange("walletPlugin.logoDark", value)}
              disabled={!walletPlugin.enable}
            />
          </Card>
        )}
        <div className="flex justify-center">
          <Button onClick={connect} className="w-full !h-auto group py-3 rounded-full flex items-center justify-center">
            Connect
          </Button>
        </div>
      </Card>
    </div>
  );
};

export default AppSettings;
